#!/bin/sh
ftolower() 
{ 
        lname=$(basename "$1" | tr 'A-Z' 'a-z');
        lpath=$(dirname "$1")'/'$lname;
        echo $lpath;
        [ -f "$lpath" ] && echo "Kolize na soubor $lpath" || mv "$1" "$lpath";
}

ftoupper() 
{ 
        lname=$(basename "$1" | tr 'a-z' 'A-Z');
        lpath=$(dirname "$1")'/'$lname;
        echo $lpath;
        [ -f "$lpath" ] && echo "Kolize na soubor $lpath" || mv "$1" "$lpath";
}

r=false
if [ $# -eq 0 ] || [ $# -eq 1 ] && [ "$1" == "-r" ]; then 
{
        if [ "$1" == "-r" ]; then 
        {
                for myfile in $(find . -type f -not -name "[A-Z]*"); 
                        do ftoupper "$myfile"; done;
        };
        else 
        {
                for myfile in $(find . -type f -not -name "[a-z]*");
                        do ftolower "$myfile"; done;
        }
        fi;
        
}; 
fi;
while test $# -gt 0
do
    if [ "$1" == "-r" ]; then r=true; 
    elif [ "$r" == true ]; then 
    {
        for myfile in $(find "$1" -type f -not -name "[A-Z]*"); 
                do ftoupper "$myfile"; done;
    }
    else 
    {
        for myfile in $(find "$1" -type f -not -name "[a-z]*");
                do ftolower "$myfile"; done;
    }
    fi;
    shift;
done

